title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
  banner-btn:
    title: "Banner Btn"
    description: |
      The banner btn is used on the banner as a call to action.
