title: "Banners"
description: |
  Banners should be used as a call to action at the top of a web page. There should only be one per page.

patterns:
  banner-main:
    height: 800
    fields:
      - name: heading
        type: string
        example:  "Immerse Yourself."
      - name: text
        type: string
        example:  "With one light, our candles can emulate the scent of your paradise."
